// Generated by https://quicktype.io

export interface Productos {
    status: string;
    result: Result;
}

export interface Result {
    code: string;
    msg:  Msg;
}

export interface Msg {
    productos: Producto[];
}

export interface Producto {
    id:        string;
    nombre:    string;
    descuento: null;
    precio:    string;
    imagen:    string;
}
